### ISSUE TITLE
problem with '*' in .gitignore

### ISSUE THREAD

**Issue by thefab** [mherrmann/gitignore_parser#1]
Hi,

I try to set a .gitignore file like this one:

https://stackoverflow.com/questions/8024924/gitignore-ignore-all-files-then-recursively-allow-foo/8025106#8025106

It doesn't work with this library.

If you try with a a simple `.gitignore` file with:

```
*
```

You got something like that:

```
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/site-packages/gitignore_parser.py", line 18, in parse_gitignore
    source=(full_path, counter))
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/site-packages/gitignore_parser.py", line 68, in rule_from_pattern
    if pattern[0] == '*' and pattern[1] == '*':
IndexError: string index out of range
```

**Comment by mherrmann** [comment]
Sorry about that. I'm no longer using this library, so don't have time to improve it. If you want to submit a PR that fixes this, I'd be happy to merge it.

**Comment by wsams** [comment]
I noticed this too while testing. I just submitted a patch for another bug. If I get time I may look into fixing this one as well.

**Comment by ahernsean** [comment]
This crash no longer happens due to changes I made while fixing negation rules. More testing is needed to validate that `*` is working properly, but quick tests pass.

**Comment by inverse** [comment]
Hi @thefab @ahernsean - I added a test case in #25 - can you confirm this covers the reported behaviour.

**Comment by ahernsean** [comment]
@inverse  Looks reasonable to me!

**Comment by mherrmann** [comment]
Then thank you both @inverse and @ahernsean  :-) I'll close this issue.
