### ISSUE TITLE
Bug with matching paths within .gitignore directory

### ISSUE THREAD

**Issue by inverse** [mherrmann/gitignore_parser#14]
Is this correct? It feels like a bug to me since it works when you specify the rule in `.gitignore`.

Imagine `.gitignore` contents including

```
.venv/
```

And a script evaluating this

```
gitignore_matcher('/path/to/repo/.venv/')
True
gitignore_matcher('/path/to/repo/.venv/bin')
False
```

To me the second one should return `True`

**Comment by mherrmann** [comment]
Yeah seems like this is a bug. You could add a test for this to [`tests.py`](https://github.com/mherrmann/gitignore_parser/blob/master/tests.py) and then implement a fix. I won't have time to do it.

**Comment by inverse** [comment]
Sure I can try and get this sorted when I have time too.

**Comment by bitranox** [comment]
@inverse , indeed, that fails ! I put the tests into the development branch of igittigitt - will You take care of it ?
https://github.com/bitranox/igittigitt/tree/development

**Comment by mherrmann** [comment]
@bitranox please stop astroturfing here. Contribute to this library, or find contributors for yours somewhere else.
