### ISSUE TITLE
Codacy integration

### ISSUE THREAD

**Issue by inverse** [mherrmann/gitignore_parser#22]
Would you be interested in setting up [codacy](https://www.codacy.com/) integration into this project? 

It's free and relatively painless aside the tuning of the tools that are are used to lint the project and can scan for multiple things like:

- security issues
- code quality
- linting

As well as it can be used to collect code coverage metrics from the test suite which I can help set up.

**Comment by mherrmann** [comment]
Thank you for the suggestion but I think it would be overkill for such a simple project.
