### ISSUE TITLE
Clear release notes

### ISSUE THREAD

**Issue by inverse** [mherrmann/gitignore_parser#23]
What's your opinion on providing clear release notes with each release so that people know what's changed between? 

I've seen some projects adopting a `CHANGELOG.md` file in the repo to track these and others leverage github to handle this.

I don't have a strong opinion on either.

**Comment by mherrmann** [comment]
I think it would be overkill for such a little project. I do keep this information in the page of GitHub releases. Thank you for the suggestion though, I appreciate it.
