### ISSUE TITLE
support parsing all .gitignore files in specified directory tree

### ISSUE THREAD

**Issue by walkingpendulum** [mherrmann/gitignore_parser#26]
[gitignore specification](https://git-scm.com/docs/gitignore#_description) states:
> when deciding whether to ignore a path, Git normally checks gitignore patterns from multiple sources [...] patterns read from a .gitignore file in the same directory as the path, or in any parent directory, with patterns in the higher level files (up to the top level of the work tree) being overridden by those in lower level files down to the directory containing the file

so it would be nice to have a way to build a list of ignore rules not only from specific .gitignore file, but from all .gitignore files in specific directory tree.

actually, for my work project I reused your code and built [custom ignore function for shutil.copytree](https://docs.python.org/3/library/shutil.html#shutil.ignore_patterns). this work I'd done can be back ported to your project, if you see idea fit your vision of this package. waiting to hear back from you to open PR.

**Comment by mherrmann** [comment]
Thank you for your comments. I don't think copying should be part of this library. But building a list of rules not just from one file from (recursively) from all files in a specific directory tree should. If you'd like to submit a PR that adds this - with associated tests in `test.py`, I'd be happy to merge it.

**Comment by excitoon** [comment]
@walkingpendulum I guess the correct algorithm shall be — for any given path, go through all parent directories and match the path against it (with their base directories). I think it can be implemented as:

```
g = gitignore_parser.GitIgnoreCache()
g(path)
```

Does that sound good to you?

**Comment by walkingpendulum** [comment]
@excitoon don't know about api choice you are suggesting here (GitIgnoreCache is not a part of this lib, afaik). but your algorithm is correct.

**Comment by excitoon** [comment]
Yeah, I gonna add this functionality (since I need it in `excitoon/3`
anyway). Is naming fine for you?

**Comment by walkingpendulum** [comment]
> Is naming fine for you?

tbh I do not see why this class is called "Cache". it does no caching, it does the same thing, as "parse" function, but with respect to gitignore files in the upstream dir tree. consider to drop one of those two approaches, so [there will be one obvious way to do it](https://peps.python.org/pep-0020/).

aside from that, looks like this is exactly, what I was asking for.

**Comment by excitoon** [comment]
I guess we shall stick to `gitignorefile.ignored(path)` then.

**Comment by excitoon** [comment]
@walkingpendulum I fixed all issues except probably negations (I don't have any failing test yet), and at the same time code became like 40x faster (30 seconds on big project with lots of submodules vs original 20 minutes).

**Comment by walkingpendulum** [comment]
@excitoon any intention to make a PR with changes into this (upstream) repo?

**Comment by excitoon** [comment]
@walkingpendulum It's nobody here, I started my own project for exactly that reason. There are also guys @bitranox with  `igittigitt` and @cpburnz with `python-path-specification` (which is used by Black for some reason). But I doubt they parse `.gitignore` better than me.

**Comment by excitoon** [comment]
Besides that, it was quite a big rework, and there is no Windows supported
by this repo.

**Comment by walkingpendulum** [comment]
great! looks, like this issue could be closed as requested feature is implemented in https://github.com/excitoon/gitignorefile
