### ISSUE TITLE
Not working without base_path given

### ISSUE THREAD

**Issue by Seluj78** [mherrmann/gitignore_parser#27]
Hi ! Thank you for the implementation, It's great but I had some trouble implementing it in https://github.com/seluj78/potodo

Here's what is happening

`.potodoignore` content
```
venv/
```

```python
from gitignore_parser import parse_gitignore
from pathlib import Path

potodoignore_path = Path("/Users/seluj78/Projects/potodo/.potodoignore")
bad_file = Path("/Users/seluj78/Projects/potodo/venv/bin/python")
matches = parse_gitignore(gitignore_path)
matches(bad_file)  # False
```

But if I change it to this, then it works

```python
from gitignore_parser import parse_gitignore
from pathlib import Path

base_path = Path("/Users/seluj78/Projects/potodo")
bad_file = Path("/Users/seluj78/Projects/potodo/venv/bin/python")
matches = parse_gitignore(".potodoignore", base_dir=base_path)
matches(bad_file)  # True
```

hope this helps !

**Comment by mherrmann** [comment]
Thank you for the feedback. If you think this should be fixed and want to submit a PR, I'd be happy to merge it.

**Comment by Seluj78** [comment]
I don't know if it is unintended behavior or just me who didn't understand how the parametters work.

Sadly, I don't have enough information to go off of with this :

https://github.com/mherrmann/gitignore_parser/blob/182d646171a95b7938430cc9cf8b1b38901b59f1/gitignore_parser.py#L18-L22

Or even here in your documentation
https://github.com/mherrmann/gitignore_parser/blob/182d646171a95b7938430cc9cf8b1b38901b59f1/README.md#L22

So I don't know if it is a bug or a documentation misshap, I'll see what I can do !

**Comment by mherrmann** [comment]
I see. I'm not sure either. But it could be verified by re-enacting with `git` on the command line.

**Comment by Seluj78** [comment]
> I see. I'm not sure either. But it could be verified by re-enacting with `git` on the command line.

I'm not sure what you mean but I've just forked and cloned your project and I'll see what I can come up with !

**Comment by Seluj78** [comment]
#28 is the WIP PR i'll work on !

**Comment by mherrmann** [comment]
What I meant was that you could create a `.gitignore` file as in your example, then type `git` on the command line to see whether a `venv/` folder would be excluded.

**Comment by Seluj78** [comment]
If you mean what I think you do, then yeah, `venv/` is excluded.

https://asciinema.org/a/JVqz4Kyh5ubLWtGSemoLWnTg5

**Comment by Seluj78** [comment]
I'm also adding Typing, because might as well, but I will need to move functions around. Is that a problem ?

**Comment by mherrmann** [comment]
I'm open to code reorganizations. Type hints are also fine. Then I'll increase the minimum Python version to 3.7.

The ASCII video you showed is what I meant. However: It is different from your very first example in this thread. Because in that example, you are asking for a file _inside_ `venv/`. Whereas in the ASCII you are effectively asking for `venv/` itself.

But I think I've figured out a way to test for compliance with `git`:

    git check-ignore venv/bin/python

This excludes `venv/bin/python`, so we should, too.

**Comment by Seluj78** [comment]
No need to increase minimum version to `3.7` ! `3.6` is fine ! Because before `3.6`, type hints in variables weren't allowed

In my original problem, I was using rglob in my project to find all `.po` files but `venv/` files were matched too, even though I had `venv/` in my ignore file

**Comment by Seluj78** [comment]
@mherrmann Ok I think I have done what I think is more logical to me. Let me know what you think !

https://github.com/mherrmann/gitignore_parser/pull/28
