### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [mherrmann/gitignore_parser#44]
Could you please tag the source again? This allows distributions to get the complete source from GitHub if they want.

[0.1.2](https://github.com/mherrmann/gitignore_parser/tree/v0.1.2) was tagged but not [0.1.3](https://pypi.org/project/gitignore-parser/0.1.3/).

Thanks

**Comment by mherrmann** [comment]
Hi, what do you mean by tagging? Tagging where? There is a [git tag for 0.1.3](https://github.com/mherrmann/gitignore_parser/tree/v0.1.3).

**Comment by fabaff** [comment]
Hmmm, sorry for the noise. Yes, the tag is there.

I was working on Nixpkgs (https://github.com/NixOS/nixpkgs/pull/233759) but now everything seems fine. I guess the issue is/was at my end. Thanks, @mherrmann.
