### ISSUE TITLE
foo/**/Bar/ not working

### ISSUE THREAD

**Issue by janwilmans** [mherrmann/gitignore_parser#8]
I tried to use ** to indicate that I want all folders called 'Bar' at any level below foo/ to be ignored. Works fine for git, but given:

.gitignore
```
foo/**/Bar/
```

and

```
ignorePatterns = gitignore_parser.parse_gitignore(ignorefile)
ignorePatterns("c:\foo\Bar\foofile")   # returns false
ignorePatterns("c:\foo\test\Bar\foofile")   # returns false
ignorePatterns("c:\foo\test\test\Bar\foofile")  # returns false
```

**Comment by janwilmans** [comment]
I workaround is to use 
```
foo/**/Bar/**
``` 

but that is then not the same as the allowed .gitignore syntax

**Comment by janwilmans** [comment]
I guess its not really bug, depending on how the intended use is specified.

`c:\foo\Bar\foofile` technically does not match `foo/**/Bar/` however, the desired effect of ignoring the directory usually (always?) that everything below the directory is also ignored.

If you use the match to walk a directory structure and you match the rules against each directory before entering, that gives the desired effect.

However, if you are filtering a list of files as a post-processing step (like I am), then you would want  `foo/**/Bar/` to match  `c:\foo\Bar\foofile` as well....

**Comment by inverse** [comment]
Hi @janwilmans I added a test case in https://github.com/mherrmann/gitignore_parser/pull/24

Which should cover your example you mentioned. Can you confirm?
